### PR TITLE
speed improvements

### PR DESCRIPTION
**Pull request by wolfv**
See ElastoPlasticQPot

### CODE REVIEW

**Comment by tdegeus** [comment]
@wolv If I understand correctly does the `unchecked` method avoid several checks. What I find a little bit counter intuitive is that I would expect that the mechanism to switch checks on/off is using compiler flags. Can you argue this a bit?

**Comment by wolfv** [comment]
IMO unchecked is actually a misnomer. The idea behind unchecked is that it doesn't behave like the "regular" `operator()` which supports broadcasting.

So with unchecked you get an even more raw access that offers two benefits:

- it doesn't fill up indices, like the regular access currently does (which is pretty slow for xarray loops, but "free" for loops with know-dim containers such as xtensor)
- we check the layout type and derive information from this (with PR https://github.com/QuantStack/xtensor/pull/1060 ) -- for row_major it is known that the last dim has a stride of `1` so we can remove the multiplication, for col major the reverse is true (i.e. stride@0 == 1)

The latter seems to have a very positive effect on the performance in the code you gave me at these two places where I added unchecked. 

I am also arguing that we should drop the `unchecked` and make it the default behavior, and add another accessor called `broadcast()` which would exhibit the current default behavior. https://github.com/QuantStack/xtensor/issues/993 feel free to support this if you're in favor!

**Comment by wolfv** [comment]
I can't actually find the docs reference to our indexing mechanism but the default indexing at the moment is so that if you have a broadcasted xfunction, e.g. `A + B`, where e.g. A is 3D and B is 1D this equality still holds:

```
(A + B)(i, j, k) == A(i, j, k) + B(i, j, k);
```

**Comment by tdegeus** [comment]
Manually incorporated all in current master.

**Pull request closed without merging**
